server:
  port: 2222

spring:
  application:
    name: compute-service
  boot:
    admin:
      client:
        url: http://localhost:8088
  # datasource:
    # url: jdbc:mysql://10.200.131.8:3306/test?characterEncoding=utf-8&useSSL=false
    # username: root
    # password: XpPFasx15UdKszmQ8f6R
    # driver-class-name: com.mysql.jdbc.Driver
  datasource:
      platform: h2
      url: jdbc:h2:mem:computedb;MODE=MYSQL;DB_CLOSE_DELAY=-1
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop

  cloud:
    config:
      profile: dev
#  cloud:
#    consul:
#      host: 10.200.131.8
#      port: 8500
#      discovery:
#        #注册到consul的服务名称
#        serviceName: computer-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
