server:
  port: 7001

spring:
  application:
    name: pine-cloud-config-server
  cloud:
    config:
      git:
        uri: https://github.com/frankliu/pine-cloud-examples
        searchPaths: config-repo
        username: mocker
        password: mockpwd
        basedir: target/config

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:1111}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS