server:
  port: 8088

spring:
  application:
    name: pine-cloud-admin-server
  boot:
    admin: #configs to connect to self register the admin server as a client
      url: http://localhost:8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

management.security.enabled: false

