server:
  port: 2222

spring:
  application:
    name: compute-service
  boot:
    admin:
      client:
        url: http://localhost:8088
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:7001/
  datasource:
    url: jdbc:mysql://10.200.131.8:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: XpPFasx15UdKszmQ8f6R
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:1111}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
