server:
  port: 9090

spring:
  application:
    name: pine-cloud-admin-server
  boot:
    admin: #configs to connect to self register the admin server as a client
      url: http://localhost:9090
      client:
        url: http://localhost:9090

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


