package io.pine.cloud.user.domain.shared;

/**
 * @author hzliuj
 * @sinace 2017/9/1
 */

import org.springframework.util.Assert;

import javax.persistence.Embeddable;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the web.
 *
 */
@Embeddable
public final class TrackingId implements ValueObject<TrackingId> {

    private String id;

    /**
     * Constructor.
     *
     * @param id Id string.
     */
    public TrackingId(final String id) {
        Assert.notNull(id, "trackingId is required!");
        this.id = id;
    }

    /**
     * @return String representation of this tracking id.
     */
    public String idString() {
        return id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TrackingId other = (TrackingId) o;

        return sameValueAs(other);
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    @Override
    public boolean sameValueAs(TrackingId other) {
        return other != null && this.id.equals(other.id);
    }

    @Override
    public String toString() {
        return id;
    }

    TrackingId() {
        // Needed by Hibernate
    }
}
